//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookScraper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookScraper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;content&quot; class=&quot;site-content&quot; role=&quot;main&quot;&gt;
        ///
        ///		
        ///			&lt;article id=&quot;post-130&quot; class=&quot;post-130 post type-post status-publish format-standard hentry category-translations tag-dou-po-cang-qiong tag-doupo-cangqiong tag-doupocangqiong tag-translated tag-xiao-mei tag-xiao-xun-er tag-xiao-yan&quot;&gt;
        ///	&lt;header class=&quot;entry-header&quot;&gt;
        ///				&lt;h1 class=&quot;entry-title&quot;&gt;Dou Po Cang Qiong Chapter&amp;nbsp;1&lt;/h1&gt;	&lt;/header&gt;&lt;!-- .entry-header --&gt;
        ///
        ///	&lt;div class=&quot;entry-content&quot;&gt;
        ///		&lt;p&gt;Chapter 1 Genius No More&lt;/p&gt;
        ///&lt;p&gt;&amp;#8216;Dou Zhi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BattleThroughHeavens1 {
            get {
                return ResourceManager.GetString("BattleThroughHeavens1", resourceCulture);
            }
        }
    }
}
